### ISSUE TITLE
[UI] upload input validation

### ISSUE THREAD

**Issue by fbielejec** [phylogeography/spread#109]
# Problem

Validate all uploadable inputs before uploading them to s3. That includes

- sizes (use sensible defaults, a little larger for .trees files, 100 MB?)
- file types (e.g. check if tree is a Nexus file, if log or locations file has correct separators etc)

Use error reporting below the upload buttons to display a meaningful error message, e.g.:

- not a NEXUS format
- not a properly formatted locations file
- size too big, use files < 100MB

**Comment by jpmonettas** [comment]
@fbielejec What is the criteria to know if a tree is a Nexus file or if logs or locations file are correct?

**Comment by fbielejec** [comment]
> @fbielejec What is the criteria to know if a tree is a Nexus file or if logs or locations file are correct?

**Tree**
It will generally look like this:
```
#NEXUS

Begin taxa;
        Dimensions ntax=104;
        Taxlabels
                'AF196835_Pc_40.77_73.96_1999.71'
                 ...
               'WG149_Hs_34.24_118.52_2007.63'
                ;
End;

Begin trees;
        Translate
                1 'AF196835_Pc_40.77_73.96_1999.71',
                ...
               104 'WG149_Hs_34.24_118.52_2007.63'
                ;
tree TREE1 = [&R] (...)
End;
```
There will be a taxa block (tree tip labels), follow by trees block, starting with a mapping between tips and labels followed finally a tree in a newick format (it's a lisp :) )
So a good heuristic is to check if the first line contains "#NEXUS". You can get fancy and spec it, but it's not super necessary. General format description: [Nexus](https://en.wikipedia.org/wiki/Nexus_file)

**trees file** 

Similar but trees block will have multiple newick trees (tree TREE1=() tree TREE2=() etc)

**Locations file** 

This input will look like this :

```
Fujian	25.917	118.283
Guangdong	22.87	113.483
Guangxi	23.6417	108.1
Hebei	39.3583	116.6417
Henan	33.875	113.5
HongKong	22.3	114.167
Hunan	27.383	111.517
```
It will have three whitespace (tab or space(s), '\\s+') delimited columns: location names, latitude and longitude. 
All the values of the attribute selected as the "location attribute" need to have a coordinate entry in that file - but that is harder to check while uploading these inputs, and the server (the worker) will throw in that case, which is then reported in the error tab of the results page

**Log file**

There will be comment lines (ignored by the parser) and again a whitespace-delimited columnar file.
Parser is only interested in the columns called `indicators<n>` and this is what it uses to calculate BayesFactor values.

```
# BEAST v1.5.3, Build r2376
# Generated Sun Nov 22 17:32:48 CET 2009 [seed=1258907565004]
state   rates1  rates2  rates3  rates4  rates5  rates6  rates7  rates8  rates9  rates10 rates11 rates12 rates13 rates14 rates15 rates16 rates17 rates18 rates19 rates20 rates21 indicators1     indicators2     indicators3     indicators4     indicators5     indicators6     indicators7     indicators8     indicators9
     indicators10    indicators11    indicators12    indicators13    indicators14    indicators15    indicators16    indicators17    indicators18    indicators19    indicators20    indicators21    nonZeroRateCount        geoSiteModel.mu
0       1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0
     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0
     1.0     1.0     1.0     21.0    0.1
10000   1.2581321235354366      0.22495398557837346     0.511048430122912       1.2913263272363784      0.11029208596068245     1.2344205878533643      1.670492717434967       0.17233214993130855     1.4488025899449928      3.2709598720763946      4.667647067349368       0.13305963829751422     0.049566709966832156
    0.42201592492711093     3.996450333195128       0.43453581127489516     0.24722786597853336     0.7757782517627416      0.9070240426610626      1.6533029145772273      0.3505022374997808      1.0     0.0     1.0     0.0     0.0     1.0     1.0     0.0     0.0     0.0     1.0     0.0     0.0     1.0     0.0     1.0     0.0     1.0     0.0     1.0     0.0     9.0     0.4879995941828991
```
Each indicator is a numerical value that indicates a support for a from:to line (a direction of spread). Each row is liek an observation and roughly speaking the calculated BayesFactor support value for a from:to line is an average of all those rows.

As you can probbaly guess this means that the number of locations in the locations file has a strict relationship between number of locations:

```
        Boolean symmetrical = null;
        if (ncol == numberOfLocations * (numberOfLocations - 1)) {
            symmetrical = false;
        } else if (ncol == (numberOfLocations * (numberOfLocations - 1)) / 2) {
            symmetrical = true;
        } else {
            int n1 = (int) ((Math.sqrt(4 * ncol + 1) + 1) / 2);
            int n2 = (int) ((Math.sqrt(8 * ncol + 1) + 1) / 2);
            throw new SpreadException("Number of rate indicators (" + ncol + ")" + " does not match the number of locations!" + " Specify "
                                      + n2 + " locations if the location exchange models is a symmetrical one, or " + n1
                                      + " for a non-symmetrical one.");
        }
```

so there can be a symmetrical model (no difference between a->b and b->a) or an asymmetrical one, where the direction of the spread does matter (in most of the cases this is what ppl will be using). But again this relation is hard to check when uploading and is checked by the server when parsing.

**Comment by fbielejec** [comment]
Validation is just silently ignoring the files (discrete tree analysis but concerns also continuous tree)
https://user-images.githubusercontent.com/468572/141439495-9a8a0fa2-e247-4902-a462-adf0fb70ad5c.mp4

Please add a red notification below the input with an appropriate message:

- Not a tree file in Newick format
- Not a trees file in Newick format
- Not a properly formatted locations file
- Not a BEAST log file

**Comment by fbielejec** [comment]
Could we display the errors below the inputs that they concern?

![2021-11-12-1636708328_screenshot_3000x1920](https://user-images.githubusercontent.com/468572/141441766-ea0702b2-44cc-41b9-9bea-f7a3ec766756.jpg)

**Comment by fbielejec** [comment]
This could ruin your day :smile_cat: 

![2021-11-12-1636708977_screenshot_3000x1920](https://user-images.githubusercontent.com/468572/141443319-edeefb4c-37b9-4a4b-85e3-ea7a6ef75dbb.jpg)

These values should be strictly positive (> 0)
