### ISSUE TITLE
[Viewer] Missing maps url argument

### ISSUE THREAD

**Issue by fbielejec** [phylogeography/spread#116]
# Problem

I can reproduce it locally and in production

![missing_maps](https://user-images.githubusercontent.com/468572/138150740-114df1c3-03ff-499c-8c73-4893bf8e2a5a.jpg)

**Comment by jpmonettas** [comment]
I wasn't able to reproduce it locally nor on prod, so closing it for now
![latest-screenshot](https://user-images.githubusercontent.com/786299/138278406-6618a485-ed4f-4a17-a4f8-47e56bf974c0.png)
