### ISSUE TITLE
[UI] Upload indicator not visible

### ISSUE THREAD

**Issue by fbielejec** [phylogeography/spread#117]
# Problem

Upload progress indicators not displaying. I could reproduce it on every analysis type, but posting just for Continuous Tree 

https://user-images.githubusercontent.com/468572/138151758-f5a1830f-278b-4858-9ed6-5906a550d601.mp4

## Notes

Potentially to be done together with #108

**Comment by jpmonettas** [comment]
This looks fine locally, it isn't showing because progress is reported only once with 100%.
This fn here https://github.com/fbielejec/SPREAD/blob/master/src/cljs/ui/events/continuous_mcc_tree.cljs#L44-L45 is always being called once with sent = total, so there is no progress to show.
