### ISSUE TITLE
[Viewer] Icons not rendering properly, outdated icon

### ISSUE THREAD

**Issue by fbielejec** [phylogeography/spread#125]
# Problem

![2021-11-05-1636137929_screenshot_3000x1920](https://user-images.githubusercontent.com/468572/140613508-5f11191e-3fea-49a3-a191-1bcfe5f51076.jpg)

At the same time please update the main icon to the [icn_spread.svg](https://github.com/fbielejec/spread/blob/master/services/ui/icons/icn_spread.svg) resource.

**Comment by jpmonettas** [comment]
This was fixed by 9612e4f
