### ISSUE TITLE
ContinuousTree result with no maps argument after parsing

### ISSUE THREAD

**Issue by fbielejec** [phylogeography/spread#126]
# Problem

I can consistently reproduce the problem with the attached input file.
[WNV_relaxed_geo_gamma_MCC.tre.zip](https://github.com/fbielejec/spread/files/7490646/WNV_relaxed_geo_gamma_MCC.tre.zip)

![2021-11-06-1636209727_screenshot_3000x1920](https://user-images.githubusercontent.com/468572/140613636-6b2ea3bf-97c5-420e-aac6-c09caf6810f5.jpg)

**Comment by jpmonettas** [comment]
This is not a bug, the problem there is that coordinates are inverted in that file so x should be locataion2 and y location1 attributes.
If you put it the other way around the coordinates end up in the middle of the ocean and that is why no detail map is found.
Using the correct attributes settings calculates like this :
![latest-screenshot](https://user-images.githubusercontent.com/786299/142622656-b00b3ee0-1c63-46ae-8f38-6e534c348517.png)
