### ISSUE TITLE
"attribute" filter pauses animation

### ISSUE THREAD

**Issue by KanikaNahata** [phylogeography/spread#163]
Spread link: https://view.spreadviz.org/?output=94d05c76-0585-43f9-99d8-9e13973ebba0/f97a0171-7836-4f7c-8dc0-d4eeef938d21.json&maps=DK,FR,RU,BE,UK,PT,SE
Browser: Safari, Chrome

# Problem
 Animation pauses when a filtering attribute is added.

## Screenshots

Screenshot 1: "posterior" was added during the animation and it did not move forward.
<img width="1732" alt="screenshot1" src="https://user-images.githubusercontent.com/29096492/150810922-4b48200d-96ca-4de9-ac8f-30e8203b96a5.png">

Screenshot 2: "country.states" was added at the beginning of the animation and it did not start.
<img width="1732" alt="screenshot2" src="https://user-images.githubusercontent.com/29096492/150810936-b3da9b5f-f14d-42b1-9117-6ff5d1eb4cec.png">

## Files needed to reproduce
[SARS-CoV-2discrete.zip](https://github.com/fbielejec/spread/files/7940690/SARS-CoV-2discrete.zip)

**Comment by fbielejec** [comment]
I could not immediately reproduce, can you check @jpmonettas pls?

**Comment by jpmonettas** [comment]
@KanikaNahata @fbielejec The whole thing of removing/adding objects while the animation is running is tricky and to be honest I didn't designed for it. I don't see it being super helpful but I can see someone trying that and being confused about it, maybe we can disable some of the tools while the animation is running?

**Comment by fbielejec** [comment]
Closing, goes against initial design, too deep of changes required
