### ISSUE TITLE
circle disappears when "count" from dropdown list is selected

### ISSUE THREAD

**Issue by KanikaNahata** [phylogeography/spread#164]
# Problem

Circle disappears when "count" is selected from the drop-down list
Browser: Safari, Chrome

## Analysis 1:
Spread link: https://view.spreadviz.org/?output=ddf9ff80-334a-475d-8cdd-901925a32877/f755822e-7743-4e97-ad71-d7f3303bae88.json&maps=GH,BF,GN,SL,TG

<img width="1732" alt="circle_disappears1" src="https://user-images.githubusercontent.com/29096492/151145268-4696968e-1cfd-4345-bb45-06b62b2e3fcf.png">

Files: [chiefdom_ebola.zip](https://github.com/fbielejec/spread/files/7940795/chiefdom_ebola.zip)

## Analysis 2:
Spread link: https://view.spreadviz.org/?output=94d05c76-0585-43f9-99d8-9e13973ebba0/f97a0171-7836-4f7c-8dc0-d4eeef938d21.json&maps=DK,FR,RU,BE,UK,PT,SE

<img width="1732" alt="circle_disappears2" src="https://user-images.githubusercontent.com/29096492/151145282-a558709c-0a98-49ed-a3f4-7e94ebd3a10f.png">

Files: [SARS-CoV-2discrete.zip](https://github.com/fbielejec/spread/files/7940709/SARS-CoV-2discrete.zip)

**Comment by fbielejec** [comment]
Could not repro, closing
![2022-02-14-1644855147_screenshot_3000x1920](https://user-images.githubusercontent.com/468572/153901958-e56a0b73-b5a9-42c1-9491-944cfee5878f.jpg)

**Comment by fbielejec** [comment]
Hmm, maybe you mapped the colors between white and white with transparency on? That would make them almost invisible
