### ISSUE TITLE
Overlapping map boundaries when merging some maps

### ISSUE THREAD

**Issue by KanikaNahata** [phylogeography/spread#167]
# Problem

The map is incorrect as:

### Boundaries overlap
<img width="2491" alt="image" src="https://user-images.githubusercontent.com/29096492/151526981-514420fd-7295-485d-b7e3-3bd4b0176061.png">

### European boundaries overlap and show the boundaries as distinct polygon shapes (see Switzerland), labels are overlapped and/or hidden    
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/29096492/151527706-a387d2bb-5ae6-4b0e-aeb1-fe6e36a22787.png">
<img width="788" alt="image" src="https://user-images.githubusercontent.com/29096492/151527888-3df60bb7-ecd7-4b68-a9cf-264cae579a3c.png">

### Some labels are outside the continent
<img width="2027" alt="map2" src="https://user-images.githubusercontent.com/29096492/151526617-51cc7761-37d4-4bf6-bfff-442f25230eee.png">

### Water bodies must be shown and coloured blue
<img width="2046" alt="image" src="https://user-images.githubusercontent.com/29096492/151531377-080560a1-9e49-46dc-a204-1c8ab9d62c0b.png">

Spread link for viewing the map: https://view.spreadviz.org/?output=94d05c76-0585-43f9-99d8-9e13973ebba0/f97a0171-7836-4f7c-8dc0-d4eeef938d21.json&maps=DK,FR,RU,BE,UK,PT,SE

**Comment by fbielejec** [comment]
Not sure if we can do sth about this @jpmonettas sifted the internet and the darkweb for the most comprehensive set of (free) geojson maps. Closing?
