### ISSUE TITLE
allow users to upload their own map

### ISSUE THREAD

**Issue by KanikaNahata** [phylogeography/spread#168]
# Problem

Allowing users to upload their own map if they wish. This would ensure visualization to be as detailed as they want: at a state level, district level etc. 

### Example of a chiefdom analysis in Sierra Leone
Spread link: https://view.spreadviz.org/?output=ddf9ff80-334a-475d-8cdd-901925a32877/f755822e-7743-4e97-ad71-d7f3303bae88.json&maps=GH,BF,GN,SL,TG
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/29096492/151531046-da033c9c-6f7e-4ece-8e61-8266d0dcf265.png">

**Comment by fbielejec** [comment]
Definitely useful 

- [ ] needs wire-frames from a designer.
- [ ] an ADR on how to implement

**Comment by fbielejec** [comment]
closed by #195
