### ISSUE TITLE
drop-down list for circles, nodes, etc.

### ISSUE THREAD

**Issue by KanikaNahata** [phylogeography/spread#169]
# Problem
Circle/node size or occurrence does not change when parameters are changed.

Spread link: https://view.spreadviz.org/?output=ddf9ff80-334a-475d-8cdd-901925a32877/af15cdb0-df4a-4aef-86d9-642119a9da5e.json&maps=GH,SN,BF,GW,GN,SL,ML
<img width="2501" alt="image" src="https://user-images.githubusercontent.com/29096492/151776722-12868999-3174-42c7-8f7a-fbe11a27128a.png">
![dropdown_list2](https://user-images.githubusercontent.com/29096492/151776082-b5d80bf4-5a6f-46b2-8486-bfba594746ad.png)

**Comment by fbielejec** [comment]
Feature, not a bug - attributes map to color schemes only, sizes are fixed constants (for all objects on the map), this was one of the requirements?
Should we want an extra mapping between attributes and sizes create another ticket pls, mark it with a V2 label
