### ISSUE TITLE
drop-down list names

### ISSUE THREAD

**Issue by KanikaNahata** [phylogeography/spread#170]
# Problem

The names for the drop-down list are parameter names that might not be user-friendly. 

Spread link: https://view.spreadviz.org/?output=ddf9ff80-334a-475d-8cdd-901925a32877/af15cdb0-df4a-4aef-86d9-642119a9da5e.json&maps=GH,SN,BF,GW,GN,SL,ML
![dropdown_list2](https://user-images.githubusercontent.com/29096492/151776999-14e1a7cb-f644-483f-9db3-dffb4a06cbde.png)

**Comment by fbielejec** [comment]
Not sure what to do here, those are attribute names as parsed from the data. Closing
