### ISSUE TITLE
[bug] Visualizer component throws when selecting objects

### ISSUE THREAD

**Issue by KanikaNahata** [phylogeography/spread#171]
# Problem

Displays object number when left-clicked on a layer of objects + hangs often when a layer of objects is clicked. 

Spread-link: 
<img width="2501" alt="image" src="https://user-images.githubusercontent.com/29096492/151779654-b7d4ee6d-d5e2-4027-84fa-c487228042ab.png">
![object-number-hangs](https://user-images.githubusercontent.com/29096492/151779871-e6d9e3aa-527c-4263-8bab-36ba75be6323.png)

**Comment by fbielejec** [comment]
@jpmonettas looks like overflow or sth?

I could repro on 
https://view.spreadviz.org/?output=ddf9ff80-334a-475d-8cdd-901925a32877/af15cdb0-df4a-4aef-86d9-642119a9da5e.json&maps=GH,SN,BF,GW,GN,SL,ML

```
main.js:313 Error: <g> attribute transform: Expected number, "translate(-Infinity -Infin…".
D @ main.js:313
main.js:313 Error: <rect> attribute y: Expected length, "-Infinity".
D @ main.js:313
```

**Comment by jpmonettas** [comment]
Hmm I have seen that in the past but I couldn't reproduce it now, tried many times with different amount of objects displaying on the screen and different zoom levels. Maybe if someone can capture a video of it so I can see the screen configuration that makes that happen.
