### ISSUE TITLE
polygons do not show any information

### ISSUE THREAD

**Issue by KanikaNahata** [phylogeography/spread#174]
# Problem

It is possible to click on the polygon but it reveals no information. Maybe show surface area?  

Spread link: https://view.spreadviz.org/?output=ddf9ff80-334a-475d-8cdd-901925a32877/b1994460-1a73-41b1-a728-9290c1375c35.json&maps=GH,NG,CM,BF,GN,SL,ML
<img width="2501" alt="image" src="https://user-images.githubusercontent.com/29096492/151782003-28decd74-98e2-4775-8bac-9c489e22c151.png">
<img width="2501" alt="image" src="https://user-images.githubusercontent.com/29096492/151782368-ffe64ba7-af38-4e21-902a-bc9c7b2c00fe.png">

**Comment by fbielejec** [comment]
@jpmonettas we do not have the surface area, but maybe we could display attributes of an object?

**Comment by jpmonettas** [comment]
@KanikaNahata nice catch, completely forgot to add polygon information, fixed in (https://github.com/fbielejec/spread/pull/187)

**Comment by feilongzh** [comment]
> # Problem
> It is possible to click on the polygon but it reveals no information. Maybe show surface area?
> 
> Spread link: https://view.spreadviz.org/?output=ddf9ff80-334a-475d-8cdd-901925a32877/b1994460-1a73-41b1-a728-9290c1375c35.json&maps=GH,NG,CM,BF,GN,SL,ML <img alt="image" width="2000" src="https://user-images.githubusercontent.com/29096492/151782003-28decd74-98e2-4775-8bac-9c489e22c151.png"> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/29096492/151782368-ffe64ba7-af38-4e21-902a-bc9c7b2c00fe.png">
Dear fbielejec and KanikaNahata,
I met a problem in the process of uploading files.
I don't know how to generate the correct format of uploading tree files. I have finished the tree file by running beast2. However, a mistake occurred when ongoing data analysis.
    Error ocurred while running analysis
Check full report
com.spread.exceptions.SpreadException: Can't get a discrete node state for attribute name height.

![image](https://github.com/phylogeography/spread/assets/98249975/b3abdb67-d437-4a29-b474-35dadff0621f)
![image](https://github.com/phylogeography/spread/assets/98249975/08d86561-c74c-4fcf-a027-b4533b8faf59)
[00kn_dnamedian.txt](https://github.com/phylogeography/spread/files/15369499/00kn_dnamedian.txt)


Could you help me how to solve it and give me a template or demo?  
Thanks.
Dr. Zhang.
@KanikaNahata @fbielejec
