### ISSUE TITLE
animation date change hangs the webpage

### ISSUE THREAD

**Issue by KanikaNahata** [phylogeography/spread#176]
# Problem

A change in animation date using the keyboard hangs the webpage
Browser: Only Safari 

Spread link: https://view.spreadviz.org/?output=ddf9ff80-334a-475d-8cdd-901925a32877/b6cce491-3fc3-4725-9fd8-a0e56b5afa19.json&maps=RU,MX,US,BS,CA

https://user-images.githubusercontent.com/29096492/151952973-cce12118-e94f-4e8d-9080-e1fce9db09de.mov

**Comment by fbielejec** [comment]
Could not reproduce, please check @jpmonettas, if not close it

**Comment by jpmonettas** [comment]
I wasn't able to reproduce, but since tweaking the animations settings while the animation is playing is undefined behavior this PR (https://github.com/fbielejec/spread/pull/185) disables animation settings while playing which is nicer imho.
