### ISSUE TITLE
map not detailed in 'discrete:rates'

### ISSUE THREAD

**Issue by KanikaNahata** [phylogeography/spread#191]
# Problem

Map is not detailed for US states but seems to be detailed in discrete or continuous MCC.

Spread link: https://view.spreadviz.org/?output=94d05c76-0585-43f9-99d8-9e13973ebba0/ea463ad4-900e-4605-8faa-8878009944e7.json&maps=BM,FR,RU,MA,PT,PM,ES

![image](https://user-images.githubusercontent.com/29096492/156547660-7e859e95-7729-47d6-88eb-2c8cae541287.png)

**Comment by jpmonettas** [comment]
Hmm it looks like some coordinates are mixed and it is adding detail maps for erurope/russia, I can see that in the URL. 
@KanikaNahata can you attach the data used for generating it? So I can try locally

**Comment by KanikaNahata** [comment]
@jpmonettas sure, here are the files:
[batRABV.state.rates.log](https://github.com/fbielejec/spread/files/8213266/batRABV.state.rates.log)
[locationStates.txt](https://github.com/fbielejec/spread/files/8213270/locationStates.txt)
