### ISSUE TITLE
export omits some polygons of the map

### ISSUE THREAD

**Issue by KanikaNahata** [phylogeography/spread#192]
# Problem

When exporting as .svg, some parts of the map are incorrect / get omitted.

Spread link: https://view.spreadviz.org/?output=ddf9ff80-334a-475d-8cdd-901925a32877/dcfb953a-9a35-4bb6-bc15-2643036b57b0.json&maps=CN,KP,BD,RU,NP,BT,MN
![map](https://user-images.githubusercontent.com/29096492/157656095-e97fbbd7-f86c-4b14-9b56-18bc03ebf5a7.svg)

Spread link: https://view.spreadviz.org/?output=ddf9ff80-334a-475d-8cdd-901925a32877/1be4700d-3ef6-462b-8273-4af64e6b6bba.json&maps=DK,FR,RU,BE,UK,PT,SE
![map](https://user-images.githubusercontent.com/29096492/157656942-c7e13588-32f5-4dc8-b6af-327047110d92.svg)

**Comment by jpmonettas** [comment]
Hi @KanikaNahata! 
I wasn't able to reproduce it, tried both and the svg export showed everything I was seeing in the current animation frame (at least I couldn't tell anything was missing).

Can you be more specific on what you see missing?

**Comment by fbielejec** [comment]
@KanikaNahata @jpmonettas  Can I close this one?

**Comment by KanikaNahata** [comment]
> @KanikaNahata @jpmonettas Can I close this one?

Yes :)
