### ISSUE TITLE
Give a tag

### ISSUE THREAD

**Issue by starsareintherose** [phylogeography/spread#208]
# Problem

I am maintaining the spread for archlinux users, could you give a tag to this repository making jar file compileable

## Implementation

Known steps towards feature implementation.
What needs further specifying and investigating.

## Acceptance Criteria

Rules for the future PR to be accepted.

## Notes

Random notes to keep in mind while implementing it. Mostly about related issues and future plans and thoughts.

## Future Steps

Steps which should be taken after this issue has been resolved.

**Comment by fbielejec** [comment]
Dear, this release is not a binary suitable for packaging and distributing in repositories, it is a web-application and consists of multiple components. CI server produces docker images as release artifacts.
