### ISSUE TITLE
Server error 500 on post when trying to load MCC continuous tree with a long filename

### ISSUE THREAD

**Issue by SimonGreenhill** [phylogeography/spread#216]
# Problem

When I try to load a tree into spreadviz, the website hangs with the loading icon.

I've tried the latest Firefox, Safari and Chromium on OSX.

Looking at the javascript console, it looks like the POST request to upload is rejected, because the filename was too long (which I think seems like an error from the AWS bucket?). 

Renaming the file to "a" works (original filename was `dataset-bdsc-bcov-relaxed-stddiff_1682947603558.mcct.trees`)

**Comment by fbielejec** [comment]
closing as duplicate
