### ISSUE TITLE
Connect UI with the analysis viewer

### ISSUE THREAD

**Issue by fbielejec** [phylogeography/spread#79]
# Problem

We want to render the files from the analysis using the rendering engine in analysis viewer service.

## Implementation

The viewer service accepts URL to the output file as URL parameter. It can use other url parameters if needed.

The href with the link should be here:
https://github.com/fbielejec/spread/blob/master/src/cljs/ui/analysis_results/page.cljs#L161

Use the config namespace to set the host part of the link to the URL where the analysis viewer is  

## Acceptance Criteria

User can click on the results link and is taken to the complete visualisation of his results in a separate browser tab.
He/she can use the Copy button next to the href element to share the URL. 

When pasting the URL in a browser window the visualisation can be viewed.

**Comment by jpmonettas** [comment]
This is implemented in https://github.com/fbielejec/spread/pull/83
