### ISSUE TITLE
[UI] Queued items not displaying

### ISSUE THREAD

**Issue by fbielejec** [phylogeography/spread#97]
When I started an analysis the "queued" item with the progress was not displayed.
Everything went fine with the analysis:
```
 upsert-analysis {:is-new true, :of-type "CONTINUOUS_TREE", :created-on 1633087994796, :viewer-url-params "?output=8b28e9a0-f51e-44f3-af9a-d73f2eb223c3/64d692ec-9b3e-46a4-88f3-d179f5ef2b3a.json&maps=", :user-id "8b28e9a0-f51e-44f3-af9a-d73f2eb223c3", :status "SUCCEEDED", :id "64d692ec-9b3e-46a4-88f3-d179f5ef2b3a", :progress 1.0, :readable-name "WNV_relaxed_geo_gamma_MCC"}
```

![2021-10-01-1633088484_screenshot_3000x1920](https://user-images.githubusercontent.com/468572/135637811-523978d7-eb23-4211-a6cf-4f5b2102b48e.jpg)

I'll use this occasion to complain about the styling too :)

- he arrows now completely dissipated from the view, likely the long name caused that
- button is cut
- names are long and the icon is super close to it and not in the blue color as in the wireframes
- we need to add ellipsis (that css property that shortens the text and adds ...) and scrolling the text for these long names

**Comment by jpmonettas** [comment]
Couldn't reproduce in the latest version.

![latest-screenshot](https://user-images.githubusercontent.com/786299/136076842-208afe96-ac60-4d09-ad0a-c49dac8fc701.png)
